### ISSUE TITLE
Error: Cannot find module 'core-js/modules/es.string.replace.js'

### ISSUE THREAD

**Issue by erick-vallenas** [Abdullah-129/RideFlutter#1]
Node.js v20.5.0
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module 'core-js/modules/es.string.replace.js'
Require stack:
- /app/node_modules/@googlemaps/url-signature/dist/index.umd.js
- /app/node_modules/@googlemaps/google-maps-services-js/dist/serialize.js
- /app/node_modules/@googlemaps/google-maps-services-js/dist/directions.js
- /app/node_modules/@googlemaps/google-maps-services-js/dist/client.js
- /app/node_modules/@googlemaps/google-maps-services-js/dist/geolocate.js
- /app/node_modules/@googlemaps/google-maps-services-js/dist/index.js
- /app/main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:119:18)
    at /app/node_modules/@googlemaps/url-signature/dist/index.umd.js:1:79
    at Object. (/app/node_modules/@googlemaps/url-signature/dist/index.umd.js:1:807)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/@googlemaps/url-signature/dist/index.umd.js',
    '/app/node_modules/@googlemaps/google-maps-services-js/dist/serialize.js',
    '/app/node_modules/@googlemaps/google-maps-services-js/dist/directions.js',
    '/app/node_modules/@googlemaps/google-maps-services-js/dist/client.js',
    '/app/node_modules/@googlemaps/google-maps-services-js/dist/geolocate.js',
    '/app/node_modules/@googlemaps/google-maps-services-js/dist/index.js',
    '/app/main.js'
  ]
}

Node.js v20.5.0

**Comment by Abdullah-129** [comment]
Why you are running Flutter project in Node js ?🥲

**Comment by erick-vallenas** [comment]
This error is executed in the Administration API in Docker, it is the docker log

**Comment by Abdullah-129** [comment]
You must have done something wrong, Read the installation steps again

**Comment by erick-vallenas** [comment]
I just use this: wget -qO- https://uploads.ridy.io/docker-compose-flutter.yaml > docker-compose.yaml && docker-compose pull && docker-compose up -d

All the dockers start but all the api dockers restart every 15 seconds, so I read the log and says the error I post.

**Comment by Abdullah-129** [comment]
Try to reinstall nodejs….
